name: End-to-end tests
on:
  push:
    branches:
      - '**'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run cypress tests
        run: cd cypress-dashboard-app && docker-compose up
